INSERT INTO TB_USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED) VALUES (1, 'admin', '{bcrypt}$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1);
INSERT INTO TB_USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED) VALUES (2, 'user', '{bcrypt}$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1);
INSERT INTO TB_USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED) VALUES (3, 'disabled', '{bcrypt}$2y$12$dqZ5cRJ3iLJtAJ0o9pqO2eka.mVN3/P04ZerovClFVvfZtKYb9HqK', 'user', 'user', 'disabled@user.com', 0);

INSERT INTO TB_AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO TB_AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO TB_USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);
